#ifndef SPRITE_H
#define SPRITE_H

enum Sprite {
    SPRT_BACKGROUND,
    SPRT_MENU_BACKGROUND,
    SPRT_MISSILE_1,
    SPRT_MISSILE_2,
    SPRT_MISSILE_3,
    SPRT_MISSILE_4,
    SPRT_TARGET,
    SPRT_TARGET_HIT,
    SPRT_STONE,
    SPRT_STONE_HIT,
    SPRT_BOX,
    SPRT_BOX_HIT,
    SPRT_LAUNCHER,
    SPRT_LENGTH
};

#endif